<a href="https://colab.research.google.com/github/seungmin-lee-dotcom/seungmin-lee-dotcom/blob/main/numpy_practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python의 Numpy 라이브러리는 기본적인 상수 연산이 가능

In [1]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)
result_array = array * 10
print(result_array)

[[30 20]
 [40 20]]


서로 다른 형태의 Numpy 연산이 가능

In [2]:
import numpy as np

array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)
array3 = array1 + array2

print(array3)

[[0 2]
 [2 4]]


In [3]:
import numpy as np

array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
array4 = np.arange(0, 4).reshape(4, 1)

print(array3 + array4)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


마스킹 연산 (각각에 대하여 체크함)

In [ ]:
import numpy as np

array1 = np.arange(16).reshape(4, 4)
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)

Numpy 집계 함수

In [4]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


In [5]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print(array)
print("합계:", np.sum(array, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계: [24 28 32 36]
