<a href="https://colab.research.google.com/github/seungmin-lee-dotcom/seungmin-lee-dotcom/blob/main/numpy_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python의 Numpy 라이브러리는 List와 상호 변환이 가능

In [1]:
import numpy as np

array = np.array([1, 2, 3])
print(array.size) 
print(array.dtype) 
print(array[2]) 

3
int64
3


Python의 Numpy 라이브러리는 다양한 형태의 배열을 초기화 할 수 있음

In [1]:
import numpy as np

# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

# 0으로 초기화
array2 = np.zeros((4, 4), dtype=float)
print(array2)

# 1로 초기화
array3 = np.ones((3, 3), dtype=str)
print(array3)

# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0, 10, (3, 3))
print(array4)

# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[1 6 0]
 [4 2 7]
 [7 5 4]]
[[-1.5631559   0.54589515 -0.02948479]
 [ 0.64773549  1.71406116  1.0183282 ]
 [ 0.33686381  0.48065884  0.71341912]]


Numpy는 다양한 형태로 합치기가 가능

In [2]:
import numpy as np

array1 = np.array([1, 2, 3]) 
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [7]:
import numpy as np

array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
print(array1)
print(array2)
print(array3.shape)
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


Numpy의 형태를 변경

In [6]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))
print(array2)

[[1 2]
 [3 4]]


Numpy의 형태를 나누기 할 수 있음

In [11]:
import numpy as np

array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis=1)

print(left.shape)
print(right.shape)
print(right[0][1])

(2, 2)
(2, 2)
3
